name: JMeter Test

on:
  schedule:
    - cron: '00 00 * * 6' 


jobs:
  run_jmeter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Repository Contents
        run: ls -la
        
      - name: Create reports directory
        run: mkdir reports

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./Thread-group.jmx
          args: "-e -o ./reports/html/"
          results-file: result.csv
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.csv
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error
      
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_4 }} # Add your Slack webhook URL as a secret
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          WORKFLOW_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          curl -X POST -H 'Content-type: application/json' --data '{
              "text": "JMeter Backend test artifacts have been uploaded!\nWorkflow Run: '${WORKFLOW_URL}'"
            }' $SLACK_WEBHOOK_URL

